files:
  - source: /docs/en/3.1/*.md
    translation: /docs/%two_letters_code%/3.1/%original_file_name%
  - source: /docs/en/3.1/api/*.md
    translation: /docs/%two_letters_code%/3.1/api/%original_file_name%
